const vscode = acquireVsCodeApi();
const strings = {
  en: { refresh:'Refresh',overview:'Overview',global:'Global',project:'Project',profiles:'Models',sources:'Sources',activeSource:'Active source',indexStatus:'Configuration status',globalSettings:'Global defaults',globalHint:'Backend, storage and model defaults are used when a new managed source is created.',backend:'Backend',embeddingProfile:'Embedding profile',lanceRoot:'LanceDB root',apiKey:'API key',advanced:'Advanced indexing settings',testConnection:'Test connection',saveGlobal:'Save global defaults',projectSettings:'Project settings',projectHint:'Local values apply only to this workspace. Source-changing edits are planned before they run.',watcher:'Watch workspace changes',planChanges:'Plan changes',changePlan:'Change plan',apply:'Apply',displayName:'Display name',scope:'Scope',provider:'Provider',model:'Model',dimension:'Dimension',baseUrl:'Base URL',testProfile:'Test profile',saveProfile:'Save profile',deleteProfile:'Delete profile',newProfile:'New',copyProfile:'Project copy',reconcile:'Reconcile now',use:'Use',active:'Active',saved:'Saved',local:'local',inherited:'global',resetProject:'Reset to global',debounce_ms:'Debounce (ms)',bulk_change_threshold:'Bulk threshold',max_file_bytes:'Max file bytes',chunk_chars:'Chunk characters',chunk_overlap_chars:'Chunk overlap',batch_size:'Batch size',rg_path:'rg executable' },
  ru: { refresh:'Обновить',overview:'Обзор',global:'Глобальные',project:'Проект',profiles:'Модели',sources:'Источники',activeSource:'Активный source',indexStatus:'Состояние конфигурации',globalSettings:'Глобальные настройки',globalHint:'Backend, хранилище и модель используются при создании нового managed source.',backend:'Backend',embeddingProfile:'Профиль embedding',lanceRoot:'Корень LanceDB',apiKey:'API-ключ',advanced:'Расширенные настройки индексации',testConnection:'Проверить подключение',saveGlobal:'Сохранить глобальные',projectSettings:'Настройки проекта',projectHint:'Локальные значения относятся только к этому workspace. Изменения source сначала показываются как план.',watcher:'Наблюдать за изменениями workspace',planChanges:'Сформировать план',changePlan:'План изменений',apply:'Применить',displayName:'Название',scope:'Область',provider:'Провайдер',model:'Модель',dimension:'Размерность',baseUrl:'Базовый URL',testProfile:'Проверить профиль',saveProfile:'Сохранить профиль',deleteProfile:'Удалить профиль',newProfile:'Новый',copyProfile:'Копия для проекта',reconcile:'Переиндексировать',use:'Использовать',active:'Активен',saved:'Сохранено',local:'локально',inherited:'глобально',resetProject:'Сбросить к глобальным',debounce_ms:'Задержка (мс)',bulk_change_threshold:'Порог массовых изменений',max_file_bytes:'Максимальный размер файла',chunk_chars:'Размер chunk в символах',chunk_overlap_chars:'Перекрытие chunks',batch_size:'Размер batch',rg_path:'Исполняемый файл rg' }
};
const advanced = ['debounce_ms','bulk_change_threshold','max_file_bytes','chunk_chars','chunk_overlap_chars','batch_size','rg_path'];
const numeric = new Set(['debounce_ms','bulk_change_threshold','max_file_bytes','chunk_chars','chunk_overlap_chars','batch_size','dimension']);
let locale = 'en', t = strings.en, state, pendingPlan;

function localize() { document.querySelectorAll('[data-i18n]').forEach(el => { const value=t[el.dataset.i18n]; if (value) el.textContent=value; }); }
function input(form, name) { return form.elements.namedItem(name); }
function fill(form, values) { [...form.elements].forEach(el => { if (!el.name || values[el.name] === undefined) return; if (el.type === 'checkbox') el.checked=Boolean(values[el.name]); else if (el.type !== 'password') el.value=values[el.name] ?? ''; }); updateBackend(form); }
function payload(form) { const value={}; [...form.elements].forEach(el => { if (!el.name) return; if (el.type==='checkbox') value[el.name]=el.checked; else if (el.type==='password' && !el.value) return; else value[el.name]=numeric.has(el.name)?Number(el.value):el.value; }); return value; }
function updateBackend(form) { const backend=input(form,'backend')?.value; form.querySelectorAll('[data-backend]').forEach(el => { el.hidden=el.dataset.backend!==backend; }); }
function addAdvancedFields() { document.querySelectorAll('.advanced-fields').forEach(box => { advanced.forEach(name => { const label=document.createElement('label'); const span=document.createElement('span'); span.textContent=t[name]; const field=document.createElement('input'); field.name=name; field.type=numeric.has(name)?'number':'text'; label.append(span,field); if(name==='rg_path'){ const wrap=document.createElement('div'); wrap.className='path'; label.replaceChildren(span,wrap); wrap.append(field); const pick=document.createElement('button'); pick.type='button'; pick.textContent='…'; pick.dataset.pick=name; pick.dataset.kind='file'; wrap.append(pick); } box.append(label); }); }); }
function setProfiles() { document.querySelectorAll('[data-profiles]').forEach(select => { const current=select.value; const globalOnly=select.closest('form')?.id==='globalForm'; select.replaceChildren(); Object.entries(state.profiles).filter(([,p])=>!globalOnly||p.scope!=='project').forEach(([id,p]) => { const o=document.createElement('option'); o.value=id; o.textContent=p.display_name||id; select.append(o); }); if([...select.options].some(o=>o.value===current)) select.value=current; }); }
function markOrigins() { const overrides=state.project.overrides||{}; const form=document.getElementById('projectForm'); [...form.elements].forEach(el => { if(!el.name) return; const label=el.closest('label'); if(!label || label.querySelector('.origin')) return; const badge=document.createElement('small'); badge.className='origin'; badge.textContent=Object.hasOwn(overrides,el.name)?t.local:t.inherited; (label.querySelector('span')||label).append(badge); }); }
function render() {
  document.getElementById('projectPath').textContent=state.project.path; setProfiles();
  fill(document.getElementById('globalForm'),state.defaults); fill(document.getElementById('projectForm'),{...state.project.effective,watch_enabled:state.project.watch_enabled}); markOrigins();
  const s=state.project.active_source; const summary=document.getElementById('summary'); summary.replaceChildren();
  [['ID',s.id],[t.backend,s.backend],[t.embeddingProfile,s.embedding_profile],['LanceDB/Qdrant',s.location.directory||`${s.location.url} / ${s.location.collection}`]].forEach(([k,v])=>{const dt=document.createElement('dt');dt.textContent=k;const dd=document.createElement('dd');dd.textContent=v;summary.append(dt,dd);});
  document.getElementById('statusResult').textContent=JSON.stringify(state.project.index_status||{status:'ok',watch_enabled:state.project.watch_enabled},null,2);
  const list=document.getElementById('profileList'); list.replaceChildren(); Object.entries(state.profiles).forEach(([id,p])=>{const o=document.createElement('option');o.value=id;o.textContent=`${p.display_name||id} · ${p.provider}`;list.append(o);}); if(list.options.length){list.selectedIndex=0;loadProfile(list.value);}
  const rows=document.getElementById('sourceRows'); rows.replaceChildren(); state.project.sources.forEach(source=>{const tr=document.createElement('tr'); [source.id,source.backend,source.embedding_profile].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);}); const action=document.createElement('td'); const b=document.createElement('button'); const active=source.id===state.project.active_source_id;b.textContent=active?t.active:t.use;b.disabled=active;b.addEventListener('click',()=>send('useSource',{sourceId:source.id}));action.append(b);tr.append(action);rows.append(tr);});
}
function loadProfile(id, copy=false) { const p=state.profiles[id]||{}; const form=document.getElementById('profileForm'); fill(form,{...p,profile_id:copy?`${id}-${state.project.project_id.slice(0,8)}`:id,display_name:copy?`${p.display_name||id} (${t.project})`:p.display_name||id,scope:copy?'project':p.scope||'global',api_key:''}); }
function toast(result) { const el=document.getElementById('toast'); el.className=result?.status==='error'?'error':'ok'; el.textContent=result?.error||JSON.stringify(result); clearTimeout(el._timer); el._timer=setTimeout(()=>{el.className='';el.style.display='none';},5000); el.style.display='block'; }
function send(command,extra={}) { vscode.postMessage({command,...extra}); }

document.querySelectorAll('nav button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('hidden',tab.id!==`tab-${button.dataset.tab}`));}));
document.querySelector('nav button').classList.add('active');
document.querySelectorAll('select[name="backend"]').forEach(el=>el.addEventListener('change',()=>updateBackend(el.form)));
document.addEventListener('click',event=>{const b=event.target.closest('[data-pick]');if(b)send('choosePath',{target:b.dataset.pick,kind:b.dataset.kind,value:input(b.form,b.dataset.pick).value});});
document.getElementById('refresh').addEventListener('click',()=>send('refresh'));
document.getElementById('globalForm').addEventListener('submit',e=>{e.preventDefault();send('saveDefaults',{payload:payload(e.target)});});
document.querySelector('[data-action="test-global"]').addEventListener('click',e=>send('testBackend',{payload:payload(e.target.form)}));
document.getElementById('projectForm').addEventListener('submit',e=>{e.preventDefault();send('planProject',{payload:payload(e.target)});});
document.getElementById('resetProject').addEventListener('click',()=>{const form=document.getElementById('projectForm');fill(form,{...state.defaults,watch_enabled:state.project.watch_enabled});send('planProject',{payload:{clear_overrides:['backend','embedding_profile','qdrant_url','qdrant_secret_ref','lancedb_root',...advanced],watch_enabled:state.project.watch_enabled}});});
document.getElementById('applyPlan').addEventListener('click',()=>{if(pendingPlan)send('applyProject',{payload:pendingPlan});});
document.getElementById('profileList').addEventListener('change',e=>loadProfile(e.target.value));
document.getElementById('newProfile').addEventListener('click',()=>{const form=document.getElementById('profileForm');form.reset();fill(form,{scope:'global',provider:'fastembed',dimension:768});});
document.getElementById('copyProfile').addEventListener('click',()=>loadProfile(document.getElementById('profileList').value,true));
document.getElementById('profileForm').addEventListener('submit',e=>{e.preventDefault();send('saveProfile',{payload:{...payload(e.target),project_id:state.project.project_id}});});
document.getElementById('testProfile').addEventListener('click',e=>send('testProfile',{payload:payload(e.target.form)}));
document.getElementById('deleteProfile').addEventListener('click',()=>send('deleteProfile',{profileId:input(document.getElementById('profileForm'),'profile_id').value}));
document.getElementById('reconcile').addEventListener('click',()=>send('reconcile'));
window.addEventListener('message',event=>{const m=event.data;if(m.type==='state'){state=m.state;locale=m.locale||'en';t=strings[locale]||strings.en;if(!document.querySelector('.advanced-fields').children.length){localize();addAdvancedFields();}else localize();render();if(m.result)toast(m.result);}else if(m.type==='plan'){pendingPlan={...m.payload,plan_hash:m.plan.plan_hash,impact:m.plan.impact};document.getElementById('planResult').textContent=JSON.stringify(m.plan,null,2);document.getElementById('planBox').classList.remove('hidden');}else if(m.type==='path'){document.querySelectorAll(`[name="${m.target}"]`).forEach(el=>el.value=m.value);}else if(m.type==='result')toast(m.result);});
send('ready');
